### ISSUE TITLE
Add gpg key for provider to the opentofu registry

### ISSUE THREAD

**Issue by What-is-water93** [isometry/terraform-provider-deepmerge#33]
Hey,
I would like to use your provider with opentofu using the opentofu registry?    
Would it be possible for you to submit your public GPG signing key to the opentofu registry, to allow verifying the installation? There is an issue template to submit the key under https://github.com/opentofu/registry/issues/new/choose 
Thanks for making the provider!
Best regards

**Comment by isometry** [comment]
Done: [here](https://github.com/opentofu/registry/issues/733)

**Comment by What-is-water93** [comment]
Thank you!
